Multisig setup
toshmanuel/co-sign pull request #26
Opened 2022-05-12 20:35 UTC by j-kon

**What does this PR do?**

A summary of what this PR is about

**List of task completed**

-   [x] Created a set-up screen
-   [x] Modify UI

On this branch I created the a set-up screen for multisig and also the adjust UI

**How can this be tested?**

- Highlight how this PR can be tested

**Additional info**

Add more info if any. eg fixes #.

2022-05-17 13:36 UTC, toshmanuel requested changes

2022-05-17 13:36 UTC, toshmanuel commented on Frontend/lib/screens/home/key_creation.dart
> +import 'package:flutter/material.dart';
why do we have this screen, I don't think we need to set up any cosigner.

2022-05-18 09:58 UTC, toshmanuel approved these changes

2022-05-18 10:08 UTC, Muneerah1612 approved these changes

2022-05-18 10:08 UTC, Muneerah1612 commented on Frontend/lib/screens/auth/forget_password.dart
> +                  'A link will will be send to your email for password reset',
A link will be sent,not send

2022-05-18 10:08 UTC, Muneerah1612 commented on Frontend/lib/utils/constant.dart
> +const String summitYourText = 'Summit Your Key';
'Submit', always check your spelling

2022-05-18 12:43 UTC, j-kon commented on Frontend/lib/screens/auth/forget_password.dart
> +                  'A link will will be send to your email for password reset',
> A link will be sent,not send

Thanks resolve

2022-05-18 12:43 UTC, j-kon commented on Frontend/lib/utils/constant.dart
> +const String summitYourText = 'Summit Your Key';
> 'Submit', always check your spelling

Thanks resolve

2022-05-18 17:20 UTC, merged

2022-05-19 08:27 UTC, stickies-v commented
Thanks for adding screenshots to the PR! Going forward I'd avoid having bad commits in your PRs altogether. All the "added to gitignore" commits should have just been dropped or squashed before merging - plus there are still some .pyc files checked in that shouldn't be there.

2022-05-19 09:20 UTC, j-kon commented
> Thanks for adding screenshots to the PR! Going forward I'd avoid having bad commits in your PRs altogether. All the "added to gitignore" commits should have just been dropped or squashed before merging - plus there are still some .pyc files checked in that shouldn't be there.

Well noted, thanks